#!/usr/bin/env bash

# Git completion for custom git wrapper functions
#
# How it works:
# 1. Git's completion script provides functions like _git_log, _git_diff, etc.
# 2. We use bash's 'complete' command to associate our custom functions with these
# 3. When you type 'logAgainstMain --<TAB>', it routes to _git_log for completion
#
# This file was originally generated by AI.
#
# Only functions need to have completion defined here as the alias completion logic
# from bash-it will handle aliases.
#
# Functions need to be configured to pass the arguments to the underlying git command.

# Check if git completion is available
if ! declare -F __git_complete >/dev/null 2>&1; then
	return
fi

# Completion for custom git wrapper functions that should use git log completion
__git_complete logAgainstMain _git_log
__git_complete logAgainstBase _git_log
__git_complete logAgainstRemote _git_log
__git_complete previewMainMerge _git_log
__git_complete gHeadRemote _git_log

# Completion for custom git wrapper functions that should use git diff completion
__git_complete diffAgainstMain _git_diff
__git_complete diffAgainstBase _git_diff
__git_complete diffAgainstRemote _git_diff

# Completion for custom git wrapper functions that should use git rebase completion
__git_complete gRebaseBase _git_rebase
__git_complete gRebaseMain _git_rebase

# Completion for custom git wrapper functions that should use git clone completion
__git_complete clonePersonalRepo _git_clone

# Completion for custom git wrapper functions that should use git pull completion
__git_complete glum _git_pull

# Completion for custom git wrapper functions that should use git push completion
__git_complete gpu _git_push

# Completion for other git command wrappers
__git_complete mergeMainIntoBranch _git_checkout

_gitCheckoutCompletionPreferLocalBranches() {
	# Get the current word being completed.
	local cur="${COMP_WORDS[COMP_CWORD]}"

	# Get the list of local branches.
	local branches
	branches=$(git branch --format='%(refname:short)')

	# Filter branches based on the current input.
	local candidates
	candidates=$(compgen -W "${branches}" -- "${cur}")

	# If no local branches match, fall back to git's checkout completion.
	# __git_func_wrap initializes git completion internals (_git_checkout expects these).
	if [[ -z "$candidates" ]]; then
		if declare -F __git_func_wrap >/dev/null 2>&1; then
			__git_func_wrap _git_checkout
		else
			_git_checkout
		fi
		return
	fi

	# Output the candidates for completion
	COMPREPLY=()
	while IFS= read -r candidate; do
		COMPREPLY+=("$candidate")
	done <<<"$candidates"
}

# Add custom completion for gco using git's completion wrapper plumbing.
__git_complete gco _gitCheckoutCompletionPreferLocalBranches
