#!/usr/bin/env bash

# Git completion for custom git wrapper functions
#
# How it works:
# 1. Git's completion script provides functions like _git_log, _git_diff, etc.
# 2. We use bash's 'complete' command to associate our custom functions with these
# 3. When you type 'logAgainstMain --<TAB>', it routes to _git_log for completion
#
# This file was originally generated by AI.
#
# Only functions need to have completion defined here as the alias completion logic
# from bash-it will handle aliases.
#
# Functions need to be configured to pass the arguments to the underlying git command.

# Check if git completion is available
if ! declare -F __git_complete >/dev/null 2>&1; then
	return
fi

# Completion for custom git wrapper functions that should use git log completion
__git_complete logAgainstMain _git_log
__git_complete logAgainstBase _git_log
__git_complete logAgainstRemote _git_log
__git_complete previewMainMerge _git_log
__git_complete gHeadRemote _git_log

# Completion for custom git wrapper functions that should use git diff completion
__git_complete diffAgainstMain _git_diff
__git_complete diffAgainstBase _git_diff
__git_complete diffAgainstRemote _git_diff

# Completion for custom git wrapper functions that should use git rebase completion
__git_complete gRebaseBase _git_rebase
__git_complete gRebaseMain _git_rebase

# Completion for custom git wrapper functions that should use git clone completion
__git_complete clonePersonalRepo _git_clone

# Completion for custom git wrapper functions that should use git pull completion
__git_complete glum _git_pull

# Completion for custom git wrapper functions that should use git push completion
__git_complete gpu _git_push

# Completion for other git command wrappers
__git_complete mergeMainIntoBranch _git_checkout
